package com.mykovol.ProcessTracker;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * Created by VMykolaichuk on 5/23/2017.
 */
public class PTBoard extends JFrame {

    private static PTBoard PTBoardInstance = new PTBoard();
    private JTextField textBufferSize;
    private JTextField textLastSync;
    private JPanel PTBoardMain;

    static PTBoard getInstance() {
        return PTBoardInstance;
    }

    public PTBoard() {
        super("PT Board");
        $$$setupUI$$$();
        setContentPane(PTBoardMain);
        pack();
        setDefaultLookAndFeelDecorated(true);
        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        setResizable(false);
    }

    public void showForm() {
        initValues();
        setLocationRelativeTo(null);
        setVisible(true);
        toFront();
    }

    public void initValues() {
        textBufferSize.setText(String.valueOf(Buffer.getBufferSize()));
        textLastSync.setText(Buffer.getLastSyncTimeAgo().toMinutes() + "min ago " + Buffer.getLastSyncCount() + " elements");
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PTBoardMain = new JPanel();
        PTBoardMain.setLayout(new GridLayoutManager(2, 2, new Insets(15, 15, 15, 15), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Buffer Size");
        PTBoardMain.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Last Sync");
        PTBoardMain.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textLastSync = new JTextField();
        textLastSync.setEditable(false);
        PTBoardMain.add(textLastSync, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        textBufferSize = new JTextField();
        textBufferSize.setEditable(false);
        PTBoardMain.add(textBufferSize, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PTBoardMain;
    }
}
